### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by kervis** [crashmax-off/telegram-feedback#1]
two errors for me.

PHP Notice:  Undefined variable: txt in /feedback.php on line 33
PHP Warning:  file_get_contents(https://...@gmail.com%0A&lt;b&gt;Mensaje:&lt;/b&gt; pablito clavo un clavito%0A): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
 in /feedback.php on line 36

**Comment by crashmax-off** [comment]
Its so bad code, sry 😲
